export const vagas = [
    {
      titulo: "Frotend",
      empresa: "TechCo",
      dataAplicacao: new Date("2023-10-15"),
      obteveResposta: true,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-techco",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-techco",
      verAVaga: "https://www.techco.com/vagas/desenvolvedor-web",
    },
    {
      titulo: "Frotend",
      empresa: "DataTech",
      dataAplicacao: new Date("2023-10-20"),
      obteveResposta: false,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-datatech",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-datatech",
      verAVaga: "https://www.datatech.com/vagas/engenheiro-de-dados",
    },
    {
      titulo: "Frotend",
      empresa: "DesignMasters",
      dataAplicacao: new Date("2023-10-25"),
      obteveResposta: true,
      vagaEncerrada: true,
      recrutadorLinkedIn:
        "https://www.linkedin.com/in/recrutador-da-designmasters",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-designmasters",
      verAVaga: "https://www.designmasters.com/vagas/designer-ui-ux",
    },
    {
      titulo: "Backend",
      empresa: "Empresa 4",
      dataAplicacao: new Date("2023-10-5"),
      obteveResposta: true,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-4",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-4",
      verAVaga: "https://www.empresa4.com/vagas/vaga-4",
    },
    {
      titulo: "Backend",
      empresa: "Empresa 5",
      dataAplicacao: new Date("2023-10-6"),
      obteveResposta: false,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-5",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-5",
      verAVaga: "https://www.empresa5.com/vagas/vaga-5",
    },
    {
      titulo: "Frontend",
      empresa: "Empresa 6",
      dataAplicacao: new Date("2023-10-7"),
      obteveResposta: true,
      vagaEncerrada: true,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-6",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-6",
      verAVaga: "https://www.empresa6.com/vagas/vaga-6",
    },
    {
      titulo: "Fullstack",
      empresa: "Empresa 7",
      dataAplicacao: new Date("2023-10-8"),
      obteveResposta: false,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-7",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-7",
      verAVaga: "https://www.empresa7.com/vagas/vaga-7",
    },
    {
      titulo: "Backend",
      empresa: "Empresa 8",
      dataAplicacao: new Date("2023-10-9"),
      obteveResposta: true,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-8",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-8",
      verAVaga: "https://www.empresa8.com/vagas/vaga-8",
    },
    {
      titulo: "Backend",
      empresa: "Empresa 9",
      dataAplicacao: new Date("2023-10-10"),
      obteveResposta: true,
      vagaEncerrada: true,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa 9",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-9",
      verAVaga: "https://www.empresa9.com/vagas/vaga-9",
    },
    {
      titulo: "Backend",
      empresa: "Empresa 10",
      dataAplicacao: new Date("2023-10-11"),
      obteveResposta: false,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-10",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-10",
      verAVaga: "https://www.empresa10.com/vagas/vaga-10",
    },
    {
      titulo: "Fullstack",
      empresa: "Empresa 11",
      dataAplicacao: new Date("2023-10-12"),
      obteveResposta: true,
      vagaEncerrada: true,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-11",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-11",
      verAVaga: "https://www.empresa11.com/vagas/vaga-11",
    },
    {
      titulo: "Fullstack",
      empresa: "Empresa 12",
      dataAplicacao: new Date("2023-10-13"),
      obteveResposta: false,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-12",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-12",
      verAVaga: "https://www.empresa12.com/vagas/vaga-12",
    },
    {
      titulo: "Fullstack",
      empresa: "Empresa 13",
      dataAplicacao: new Date("2023-10-14"),
      obteveResposta: true,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-13",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-13",
      verAVaga: "https://www.empresa13.com/vagas/vaga-13",
    },
    {
      titulo: "Frontend",
      empresa: "Empresa 14",
      dataAplicacao: new Date("2023-10-15"),
      obteveResposta: false,
      vagaEncerrada: true,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-14",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-14",
      verAVaga: "https://www.empresa14.com/vagas/vaga-14",
    },
    {
      titulo: "Fullstack",
      empresa: "Empresa 15",
      dataAplicacao: new Date("2023-10-16"),
      obteveResposta: true,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-15",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-15",
      verAVaga: "https://www.empresa15.com/vagas/vaga-15",
    },
    {
      titulo: "Frontend",
      empresa: "Empresa 16",
      dataAplicacao: new Date("2023-10-17"),
      obteveResposta: false,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-16",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-16",
      verAVaga: "https://www.empresa16.com/vagas/vaga-16",
    },
    {
      titulo: "Backend",
      empresa: "Empresa 17",
      dataAplicacao: new Date("2023-10-18"),
      obteveResposta: true,
      vagaEncerrada: true,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-17",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-17",
      verAVaga: "https://www.empresa17.com/vagas/vaga-17",
    },
    {
      titulo: "Backend",
      empresa: "Empresa 18",
      dataAplicacao: new Date("2023-10-19"),
      obteveResposta: false,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-18",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-18",
      verAVaga: "https://www.empresa18.com/vagas/vaga-18",
    },
    {
      titulo: "Frontend",
      empresa: "Empresa 19",
      dataAplicacao: new Date("2023-10-20"),
      obteveResposta: true,
      vagaEncerrada: false,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-19",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-19",
      verAVaga: "https://www.empresa19.com/vagas/vaga-19",
    },
    {
      titulo: "Backend",
      empresa: "Empresa 20",
      dataAplicacao: new Date("2023-10-21"),
      obteveResposta: true,
      vagaEncerrada: true,
      recrutadorLinkedIn: "https://www.linkedin.com/in/recrutador-da-empresa-20",
      techLeadLinkedIn: "https://www.linkedin.com/in/tech-lead-da-empresa-20",
      verAVaga: "https://www.empresa20.com/vagas/vaga-20",
    },
  ];